# Generated by Django 5.1.1 on 2025-11-18 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_refugio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('enfermedad', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
                ('especie', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales', to='AppExamenCarlos.refugio')),
            ],
        ),
        migrations.CreateModel(
            name='Revision_Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField()),
                ('observaciones', models.TextField()),
                ('refugio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='AppExamenCarlos.refugio')),
            ],
        ),
        migrations.CreateModel(
            name='AnimalVacunas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vacunacion', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas_animales', to='AppExamenCarlos.animal')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animales_vacunados', to='AppExamenCarlos.vacuna')),
            ],
        ),
    ]
