# Generated by Django 5.1.1 on 2025-11-04 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudio_desarrollo', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plataforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Analisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('rendimiento', models.CharField(max_length=50)),
                ('resultado', models.CharField(max_length=100)),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plataformas', to='AppExamenCarlos.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sedes', to='AppExamenCarlos.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('Accion', 'Accion'), ('Aventura', 'Aventura'), ('RPG', 'RPG'), ('Deportes', 'Deportes'), ('Estrategia', 'Estrategia'), ('Simulacion', 'Simulacion'), ('Otros', 'Otros')], max_length=20)),
                ('anyo_lanzamiento', models.IntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=3)),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='AppExamenCarlos.analisis')),
                ('estudio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videojuego', to='AppExamenCarlos.estudio')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos', to='AppExamenCarlos.plataforma')),
            ],
        ),
        migrations.CreateModel(
            name='VideojuegoAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_videojuegos', to='AppExamenCarlos.analisis')),
                ('videojuego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videojuegos_analisis', to='AppExamenCarlos.videojuego')),
            ],
        ),
    ]
