# Generated by Django 5.1.1 on 2025-11-03 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabrica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ITV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_revision', models.DateField()),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais_origen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100)),
                ('anio_lanzamiento', models.IntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='AppExamenCarlos.fabrica')),
                ('itv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coche', to='AppExamenCarlos.itv')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='AppExamenCarlos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('kilometraje', models.IntegerField()),
                ('itv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='AppExamenCarlos.itv')),
            ],
        ),
        migrations.CreateModel(
            name='CocheRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='AppExamenCarlos.coche')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coches', to='AppExamenCarlos.revision')),
            ],
        ),
    ]
